### ISSUE TITLE
Custom Cells

### ISSUE THREAD

**Issue by SpaceTrucker2196** [TeehanLax/UITableViewCell-Swipe-for-Options#6]
Is it possible to use custom cells done in IB? I end up with a empty cell and not contents, but the swipe function is working.

**Comment by ashfurrow** [comment]
Yeah, you should be able to subclass `TLSwipeForOptionsCell` and then set that as your class in IB. Let me know how it goes.

**Comment by SpaceTrucker2196** [comment]
Thanks for the quick reply. Basiclly what I tried, but I copied the cell from another view. Let me try rebuilding my cell from scratch and see how it goes. I ended up seeing the content but it seems to be on the same layer as the buttons, not on the sliding layer.

**Comment by SpaceTrucker2196** [comment]
I was able to duplicate in the sample project. Drop any label or button in the content view. Then when you run you don’t see anything other then the label that’s added at runtime in the code.

**Comment by ashfurrow** [comment]
Can you add your subviews to the `scrollViewContentView`? I don't think you'll be able to do that in a nib, just in code :\

**Comment by SpaceTrucker2196** [comment]
My cell isn’t complicated so that should be fine. I just needed a 2nd label.
